# config/routes.yaml
# auth_login:
#     path: /api/login

#     controller: App\Controller\AuthController::login

# auth_signup:
#     path: /api/signup
#     controller: App\Controller\AuthController::signup

home: 
    path: /books
    controller: App\Controller\HomeController::index



